collections:
    '':
        index_paths: http://p27.arquivo.pt/nutchwax/opensearch

        server_cls: !!python/name:opensearch.OpenSearchCDXServer


# configure path to warcs here
archive_paths:
    - http://p62.arquivo.pt:8080/arcproxy/arcproxy/
    - http://p58.arquivo.pt:8080/arcproxy/arcproxy/

enable_cdx_api: true
framed_replay: true
static_routes:
          static/resources: ./static/
          static/__pywb: pywb/static/
metadata:
          search_location: http://p27.arquivo.pt